#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# git commit --amend
# husky/prepare-commit-msg,.git/COMMIT_EDITMSG,commit,HEAD

# git rebase --continue [every-commit]
# .husky/prepare-commit-msg,.git/COMMIT_EDITMSG,message

# git commit
# .husky/prepare-commit-msg,.git/COMMIT_EDITMSG

MESSAGE="message"
COMMIT="commit"

# git rebase --continue || git commit --amend
if [[ "$2" != "$MESSAGE" && "$2" != "$COMMIT" ]]
then
  exec < /dev/tty && node_modules/.bin/cz --hook || true
fi

